on:
  pull_request:
  push:
# TODO: enable for main only and tags!
#    tags:
#      - v*
#    branches:
#      - main

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x, 1.19.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
        id: go

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Setup dependencies
        run: task setup

      - name: Linter
        run: task lint

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.13', '1.14', '1.15', '1.16', '1.17', '1.18', '1.19']
    os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
        id: go

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Setup dependencies
        run: task setup

      - name: Test
        run: task test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
