on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  lint:
    name: Lint (go ${{ matrix.go }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup dependencies
        run: task setup

      - name: Linter
        run: task lint

  test:
    name: Test (go ${{ matrix.go }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.13', '1.14', '1.15', '1.16', '1.17', '1.18', '1.19']
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            go-version: '1.19'
            send-coverage: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup dependencies
        run: task setup

      - name: Test
        run: task test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.send-coverage }}
